name: Unity Tests

on:
  pull_request:
    branches:
      - dev
      - main

  workflow_dispatch:

jobs:
  editmode:
    name: EditMode Tests
    uses: Matcodeew-Projects/Git-Workflows/.github/workflows/unity-editmode-tests.yml@main
    secrets: inherit

  playmode:
    name: PlayMode Tests
    uses: Matcodeew-Projects/Git-workflows/.github/workflows/unity-playmode-tests.yml@main
    secrets: inherit